use migu;
SET NAMES utf8mb4;
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪RS 3','',1);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪RS 6','',2);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪RS 7','',3);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪R8','',4);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪TT RS','',5);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪A1','',6);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪A3(进口)','',7);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪A3(进口)新能源','',8);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪S3','',9);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪A4(进口)','',10);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪A5','',11);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪S5','',12);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪A6(进口)','',13);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪S6','',14);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪A7','',15);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪S7','',16);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪A8','',17);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪S8','',18);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪Q5(进口)','',19);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪SQ5','',20);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪Q7','',21);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪TT','',22);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奥迪','奥迪TTS','',23);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马1系','',24);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马2系旅行车','',25);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马3系','',26);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马5系','',27);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马X1','',28);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马i3','',29);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马4系','',30);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马6系','',31);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马7系','',32);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马X3','',33);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马X4','',34);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马X5','',35);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马X6','',36);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马2系','',37);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马M3','',38);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马M4','',39);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宝马','宝马M2','',40);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','A级','',41);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','B级','',42);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','C级','',43);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','CLA级','',44);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','CLS级','',45);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','E级','',46);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','G级','',47);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','GL级','',48);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','GLA级','',49);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','GLC级','',50);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','GLE级','',51);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','GLS级','',52);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','S级','',53);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','SL级','',54);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','SLC级','',55);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','R级','',56);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','V级','',57);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','X级','',58);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','凌特','',59);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','威霆','',60);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('奔驰','AMG GT','',61);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('捷豹路虎','捷豹XFL','',62);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('捷豹路虎','捷豹XE','',63);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('捷豹路虎','捷豹XJ','',64);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('捷豹路虎','捷豹XF','',65);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('捷豹路虎','捷豹F-PACE','',66);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('捷豹路虎','捷豹F-TYPE','',67);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('捷豹路虎','发现','',68);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('捷豹路虎','揽胜','',69);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('雷克萨斯','雷克萨斯CT','',70);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('雷克萨斯','雷克萨斯IS','',71);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('雷克萨斯','雷克萨斯ES','',72);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('雷克萨斯','雷克萨斯GS','',73);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('雷克萨斯','雷克萨斯LS','',74);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('雷克萨斯','雷克萨斯NX','',75);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('雷克萨斯','雷克萨斯RX','',76);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('雷克萨斯','雷克萨斯LX','',77);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('雷克萨斯','雷克萨斯RC','',78);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('沃尔沃','沃尔沃S60L','',79);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('沃尔沃','沃尔沃S90','',80);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('沃尔沃','沃尔沃XC60','',81);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('沃尔沃','沃尔沃V40','',82);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('沃尔沃','沃尔沃V60','',83);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('沃尔沃','沃尔沃V90','',84);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('沃尔沃','沃尔沃XC90','',85);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('沃尔沃','沃尔沃S60','',86);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('凯迪拉克','凯迪拉克ATS-L','',87);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('凯迪拉克','凯迪拉克CT6','',88);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('凯迪拉克','凯迪拉克XTS','',89);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('凯迪拉克','凯迪拉克XT5','',90);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('凯迪拉克','凯雷德ESCALADE','',91);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('保时捷','Panamera','',92);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('保时捷','Macan','',93);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('保时捷','Cayenne','',94);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('保时捷','保时捷718','',95);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('保时捷','保时捷911','',96);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('法拉利','812 Superfast','',97);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('法拉利','GTC4Lusso','',98);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('法拉利','California T','',99);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('法拉利','法拉利488','',100);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('英菲尼迪','英菲尼迪Q50','',101);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('英菲尼迪','英菲尼迪Q70','',102);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('英菲尼迪','英菲尼迪QX30','',103);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('英菲尼迪','英菲尼迪QX60','',104);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('英菲尼迪','英菲尼迪QX80','',105);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('英菲尼迪','英菲尼迪Q60','',106);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('DS','DS 4S','',107);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('DS','DS 5LS','',108);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('DS','DS 6','',109);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('DS','DS 5','',110);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('林肯','林肯MKZ','',111);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('林肯','林肯大陆','',112);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('林肯','林肯MKC','',113);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('林肯','林肯MKX','',114);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('林肯','领航员','',115);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('玛莎拉蒂','Ghibli','',116);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('玛莎拉蒂','总裁','',117);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('玛莎拉蒂','Levante','',118);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('玛莎拉蒂','GranCabrio','',119);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('特斯拉','MODEL 3','',120);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('特斯拉','MODEL S','',121);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('特斯拉','MODEL X','',122);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宾利','慕尚','',123);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宾利','飞驰','',124);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宾利','添越','',125);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('宾利','欧陆','',126);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('劳斯莱斯','古思特','',127);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('劳斯莱斯','魅影','',128);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('劳斯莱斯','曜影','',129);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('兰博基尼','Huracan','',130);
insert into MGSX_INFO_CAR(BRAND,MODEL,TYPE,CAR_NO) values ('兰博基尼','Aventador','',131);